import { notFound } from "next/navigation";
import { requireCustomer } from "@/lib/auth/guard";
import { getTransactionDetail } from "@/lib/queries/transaction";
import { Panel, PanelHeader } from "@/components/ui/Panel";
import { ScoreBar } from "@/components/risk/ScoreBar";
import { DecisionIntegrityGauge } from "@/components/risk/DecisionIntegrityGauge";
import { SignalList } from "@/components/risk/SignalList";
import { RiskLevelBadge } from "@/components/ui/Badge";
import { formatINR } from "@/lib/format";
import type { RiskLevelName } from "@/lib/risk/types";
import { ContinueFromRisk } from "./ContinueFromRisk";

export default async function RiskAnalysisPage({ params }: { params: { id: string } }) {
  const { session } = await requireCustomer();
  const transaction = await getTransactionDetail(params.id);
  if (!transaction || transaction.account.userId !== session.sub) notFound();

  const latest = transaction.riskAssessments[0];
  if (!latest) notFound();

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="rise">
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-signal-teal/70 mb-2">Sentinel · Risk Analysis</p>
        <div className="flex flex-wrap items-baseline gap-3">
          <h1 className="font-display text-2xl font-semibold text-cream-100">
            {formatINR(transaction.amount)} to {transaction.beneficiary.name}
          </h1>
          <RiskLevelBadge level={latest.overallLevel as RiskLevelName} />
        </div>
        <p className="text-cream-100/55 mt-1.5 text-sm">
          Deterministic, explainable scoring. No score here is generated by a language model — every point is
          traceable to a named signal below.
        </p>
      </div>

      <Panel className="rise" style={{ animationDelay: "80ms" }}>
        <PanelHeader eyebrow="Decision Integrity Engine" title="Transaction legitimacy vs. decision integrity" />
        <div className="grid sm:grid-cols-2 gap-8 items-center">
          <div className="space-y-5">
            <ScoreBar label="Transaction Legitimacy" score={latest.transactionRisk === 0 && latest.beneficiaryRisk === 0 ? 100 : 100 - Math.round(latest.transactionRisk * 0.55 + latest.beneficiaryRisk * 0.45)} invert detail="How statistically normal this payment looks, independent of the customer's state of mind." />
            <ScoreBar label="Beneficiary Trust" score={100 - latest.beneficiaryRisk} invert />
          </div>
          <DecisionIntegrityGauge integrity={latest.decisionIntegrity} />
        </div>
        <p className="text-xs text-cream-100/45 mt-5 leading-relaxed border-t border-white/8 pt-4">
          A transaction can look technically valid — correct OTP, real device, authenticated session — while the
          customer&apos;s decision is still compromised. Aegis evaluates both independently, because authentication is
          not the same thing as intent.
        </p>
      </Panel>

      <Panel className="rise" style={{ animationDelay: "140ms" }}>
        <PanelHeader eyebrow="Sentinel" title="Risk breakdown" />
        <div className="space-y-5">
          <ScoreBar label="Transaction Risk" score={latest.transactionRisk} />
          <ScoreBar label="Beneficiary Risk" score={latest.beneficiaryRisk} />
          <ScoreBar label="Behavioral Risk" score={latest.behavioralRisk} />
          <ScoreBar label="Context Risk" score={latest.contextRisk} />
          <ScoreBar
            label="Social Engineering Risk"
            score={latest.socialEngineeringRisk}
            detail={transaction.intentChecks.length === 0 ? "Not yet assessed — pending Intent Check." : undefined}
          />
        </div>
      </Panel>

      <Panel className="rise" style={{ animationDelay: "200ms" }}>
        <PanelHeader eyebrow="Explainability" title="Contributing signals" />
        <SignalList signals={latest.signals} />
      </Panel>

      <ContinueFromRisk transactionId={transaction.id} />
    </div>
  );
}
